name: air_tasker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  provider: ^6.0.0
  flutter_svg: ^2.0.10+1
  dropdown_search: ^6.0.1
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: